defaultPortal: catidoe
portals:
  - name: catidoe
    portalId: 23210758
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMvNqbzKMBIJAA0AAAAA4A0DGIbWiAsg1vDYCyju6QwyFEZRfh68-q_pyhNNxn2fRYK0LKmBOjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhShdHbSl4Oev8-z8VpRrqdXwTdjDUoDbmExUgBaAA
        expiresAt: '2022-11-24T02:49:36.206Z'
    personalAccessKey: >-
      CiQwY2M0NjUyNy00N2ZkLTQ0NzktYThkMi02N2E1ODRhOWIwOTQQhtaICxjW8NgLKhkABeaRgpPK3mgzn2WnF7RMJ5N96q8Z-sSCSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
