defaultPortal: catidoe
portals:
  - name: catidoe
    portalId: 23210758
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COG3-r7KMBIJAA0AAAAA4A0DGIbWiAsg1vDYCyju6QwyFJeQnOo0MFvI4gO7e_XvKzWb2pyROjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhTiCACA0LKPwToWD6AUwy-ueVpry0oDbmExUgBaAA
        expiresAt: '2022-11-24T04:21:34.820Z'
    personalAccessKey: >-
      CiQwY2M0NjUyNy00N2ZkLTQ0NzktYThkMi02N2E1ODRhOWIwOTQQhtaICxjW8NgLKhkABeaRgpPK3mgzn2WnF7RMJ5N96q8Z-sSCSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
